version: '3.7'

services:
    codeblog-php-fpm:
        container_name: codeblog-php-fpm
        build: ./${PHP_VERSION}
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        links:
            - codeblog-database
            - codeblog-memcached
        networks:
            - backend_network
        restart: always
    codeblog-web-server:
        container_name: codeblog-web-server
        build: ./${WEB_SERVER_TYPE}
        depends_on:
            - source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        ports:
            - '${INTERFACE}:${HTTP_PORT}:80'
            - '${INTERFACE}:${HTTPS_PORT}:443'
        links:
            - codeblog-php-fpm
        networks:
            - backend_network
        restart: always
    codeblog-database:
        container_name: codeblog-database
        build: ./${DB_SERVER_TYPE}
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        ports:
            - '${INTERFACE}:${DATABASE_PORT}:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        networks:
            - backend_network
        restart: always
    codeblog-memcached:
        container_name: codeblog-memcached
        image: memcached:1.6.12-alpine
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        ports:
            - '${INTERFACE}:11211:11211'
        networks:
            - backend_network
        restart: always
    source:
        image: alpine:latest
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - cache:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - backend_network

volumes:
    db:
        driver: local
    cache:
        driver: local

networks:
    backend_network:
        external:
            name: backend_network
        driver: bridge
